### ISSUE TITLE
Filter by tag not working

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#586]
Hello Artem,

When creating a query filter, it does not seems possible to filter by tag.

![image](https://cloud.githubusercontent.com/assets/794449/21268965/d671c7b6-c37e-11e6-8c4c-3e1931609c1c.png)

Thanks,
Samuel

**Comment by mkudelya** [comment]
Hi @sadortun 

I confirm this bug. It will be fixed according to priorities.

Thanks!

**Comment by sadortun** [comment]
@mkudelya Just found out that this applies to all enumeration like queries. For example : 
![image](https://cloud.githubusercontent.com/assets/794449/22011031/cf69dcb6-dc5a-11e6-85ff-d7cd78be1474.png)

**Comment by mkudelya** [comment]
Hi

Thank you, we took this into account.

**Comment by mkudelya** [comment]
Hi @sadortun 

The bug has been fixed in version 2.1. I'm closing the issue.
Thank you for reporting!

**Comment by sadortun** [comment]
Awesome ! Thanks

**Comment by sadortun** [comment]
@mkudelya  The issue is still there. Re-tested in 2.1

The error is no longer displayed in the query builder widget, but reports Invalid Query

![image](https://cloud.githubusercontent.com/assets/794449/25073428/967ab8b2-22b4-11e7-8607-0c4aaf0d0962.png)

![image](https://cloud.githubusercontent.com/assets/794449/25073427/8fef3c98-22b4-11e7-958e-b411595bafdc.png)
